### ISSUE TITLE
[BUG] Bad requests on the admin ui

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#375]
# 🐜 Bug Report

Repository fetch is called with the current url not with the repository url which causes tons of 404 errors and for example breaks the drawer menu.

## 👉 Steps To Reproduce

1. Go to [https://sn-app-dev.netlify.com/](https://sn-app-dev.netlify.com/)
2. Open the console
3. Login with built-in admin
4. Wait and see...

## 😯 Current behavior

![image](https://user-images.githubusercontent.com/6968860/63860793-08c0ff00-c9aa-11e9-8852-ad18cc6a34ab.png)

## 🤔 Expected behavior

The fetch requests should be send only to the repourl

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/6968860/63860793-08c0ff00-c9aa-11e9-8852-ad18cc6a34ab.png)

**Comment by gallayl** [comment]
The following scenarios has been fixed in the https://github.com/SenseNet/sn-client/pull/374 branch:
 - [x] Eliminated personal settings initialization with a blank repository (empty repo URL)
 - [x] Drawer item permission checks for unauthenticated users
 - [x] RepositoryContextProvider's default repository has been changed to the *last used* one instead of an emptry Repository
The following scenario is **NOT** covered
 - User check with an empty personal setting (no last repository). We should define a default repo for an user (that can be an SN over SN feature)
