### ISSUE TITLE
[BUG] AddButton is still active after click on sensenet logo

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#559]
# 🐜 Bug Report

If the AddButton once changed to active it will be still active after click on the sensenet logo(nav to the home '/') 

## 📦 Package / Application

admin-ui

## 🐜 Describe the bug

Once we set currentComponent or currentPath in AddButton we don't set it to null (or undefined or '' ) when we navigate to the main page '/'

## 👉 Steps To Reproduce

![addbutton_bug](https://user-images.githubusercontent.com/22347393/72811895-d7024a80-3c60-11ea-8300-02d7ee0255d1.gif)

## 🤔 Expected behavior

AddButton should be disabled this time

**Comment by herflis** [comment]
After summarizing all the issues with the AddButton and its state, @CsabaPeter and I discussed the possible solutions (from a user perspective) and we think it would be better if the button would not be rendered in such cases. There are many cases (based on hotjar recordings) when the user does not know if it is disabled or grey by design. :)

**Comment by pusztaienike** [comment]
It is resolved in #574
