### ISSUE TITLE
[BUG] CORS error on settings opening

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#855]
# 🐜 Bug Report

When I open the admin-ui from the netlify (generated url) then I would like to open the admin-ui (admin.sensenet.com) on a different browser tab I get CORS policy error on opening a settings file.
It is the same for localhost, admin.test.sensenet.com.

The only workaround is: clearing the cache.

## 📦 Package / Application

sensenet, admin-ui

## 👉 Steps To Reproduce

1. Open admin.test.sensenet.com 
2. Go to settings menu
3. Open permissions.settings
4. Open admin.sensenet.com on a new tab
5. Go to settings menu
6. Open permissions.settings
 --> CORS error

## 😯 Current behavior

I can't open settings files from 2 different tab (and site)

## 🤔 Expected behavior

No error message :) 

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/22347393/92704875-8bb5bd00-f353-11ea-9ed4-a17ab1acee88.png)

## 🌍 Your environment (for apps / examples)

- Browser:
Chrome

**Comment by tusmester** [comment]
The reason this fails is that when we request the settings binary in the first tab, **the browser caches the settings file** and tries to use that when requesting the same settings file on the second tab. This results in a CORS error, because the file is cached with the first origin. 

- firs tab (**first origin**): admin.test.sensenet.com
- second tab (**second origin**): admin.sensenet. com

When the browser tries to check with the server if the file has changed on the _second tab_, the first origin is sent - hence the cors error. The real error though is that the settings file is cached.

#### Solutions
1. quick workaround: add a random number to the request on the client when requesting a binary
2. set the correct cache header on the server when downloading a file. Currently the default is `Public` for public files and `Private` for authenticated files - the latter allows the client to cache the file. If we changed this to `NoCache` in certain cases, the browser would not cache the file and would always load it from the server.
   - [ ] let devs/portalbuilders set cacheability values **by type/path/extension** the same way as MaxAge
   - [ ] add the `settings` extension to `Portal.settings`

**Comment by herflis** [comment]
This particular bug should not be fixed especially not with a workaround :D I've made [another issue](https://github.com/SenseNet/sensenet/issues/1190) for handling binary cache in the future
