### ISSUE TITLE
[BUG] Make content public as public administrator 

### ISSUE THREAD

**Issue by huszerlbence** [SenseNet/sn-client#944]
# 🐜 Bug Report

I was unable to make a content public on sensenet.com prod repo via admin.test.sensenet.com

see video below for more details

## 🖼 Screenshots

see video:
https://sensenet-my.sharepoint.com/:v:/p/huszerlb/Ee4REJwRjbVBlCM98urIeYUBzYvmTah71O3asXSxP56FPw?e=phsaaJ

**Comment by tusmester** [comment]
The problem is that the repo admin does not have permissions for the built-in Visitor user. Adding `See` permissions on Visitor for the public admin group solves the problem. So we have to decide:

1. Add See permissions on Visitor for public admins, OR
2. Create a new custom action for making a content public and perform the operation on the backend in elevated code, without adding See permission on the Visitor content.

(hint: the Visitor user - which means anybody who is not signed in - already has See permissions for themselves, so adding it for the public admin is not a big deal)
